# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/*\n"
                                 " * MacOS Style Sheet for QT Applications\n"
                                 " * Author: Jaime A. Quiroga P.\n"
                                 " * Company: GTRONICK\n"
                                 " * Last updated: 25/12/2020, 23:10.\n"
                                 " * Available at: https://github.com/GTRONICK/QSS/blob/master/MacOS.qss\n"
                                 " */\n"
                                 "QMainWindow {\n"
                                 "    background-color:#ececec;\n"
                                 "}\n"
                                 "QPushButton, QToolButton, QCommandLinkButton{\n"
                                 "    padding: 0 5px 0 5px;\n"
                                 "    border-style: solid;\n"
                                 "border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "    border-width: 2px;\n"
                                 "    border-radius: 8px;\n"
                                 "    color: #616161;\n"
                                 "    font-weight: bold;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #fbfdfd, stop:0.5 #ffffff, stop:1 #fbfdfd);\n "
                                 "}\n"
                                 "QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
                                 "    border: 2px solid transparent;\n"
                                 "    color: #FFFFFF;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #84afe5, stop:1 #1168e4);\n "
                                 "}\n"
                                 "QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
                                 "    color: #3d3d3d;\n"
                                 "}\n"
                                 "QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
                                 "    color: #aeaeae;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n "
                                 "}\n"
                                 "QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
                                 "    color: #616161;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #dce7eb, stop:0.5 #e0e8eb, stop:1 #dee7ec);\n "
                                 "}\n"
                                 "QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, "
                                 "QDateEdit, QDateTimeEdit {\n "
                                 "    border-width: 2px;\n"
                                 "    border-radius: 8px;\n"
                                 "    border-style: solid;\n"
                                 "border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "    background-color: #f4f4f4;\n"
                                 "    color: #3d3d3d;\n"
                                 "}\n"
                                 "QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, "
                                 "QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus {\n "
                                 "    border-width: 2px;\n"
                                 "    border-radius: 8px;\n"
                                 "    border-style: solid;\n"
                                 "border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, "
                                 "stop:0 #85b7e3, stop:1 #9ec1db);\n "
                                 "border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
                                 "stop:0 #85b7e3, stop:1 #9ec1db);\n "
                                 "border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #85b7e3, stop:1 #9ec1db);\n "
                                 "border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, "
                                 "stop:0 #85b7e3, stop:1 #9ec1db);\n "
                                 "    background-color: #f4f4f4;\n"
                                 "    color: #3d3d3d;\n"
                                 "}\n"
                                 "QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, "
                                 "QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, "
                                 "QDateTimeEdit:disabled {\n "
                                 "    color: #b9b9b9;\n"
                                 "}\n"
                                 "QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, "
                                 "QDateEdit::up-button, QDateTimeEdit::up-button {\n "
                                 "    subcontrol-origin: padding;\n"
                                 "    subcontrol-position: top right;\n"
                                 "    width: 15px;\n"
                                 "    color: #272727;\n"
                                 "    border-left-width: 1px;\n"
                                 "    border-left-color: darkgray;\n"
                                 "    border-left-style: solid;\n"
                                 "    border-top-right-radius: 3px;\n"
                                 "    padding: 3px;\n"
                                 "}\n"
                                 "QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, "
                                 "QDateEdit::down-button, QDateTimeEdit::down-button {\n "
                                 "    subcontrol-origin: padding;\n"
                                 "    subcontrol-position: bottom right;\n"
                                 "    width: 15px;\n"
                                 "    color: #272727;\n"
                                 "    border-left-width: 1px;\n"
                                 "    border-left-color: darkgray;\n"
                                 "    border-left-style: solid;\n"
                                 "    border-bottom-right-radius: 3px;\n"
                                 "    padding: 3px;\n"
                                 "}\n"
                                 "QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, "
                                 "QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, "
                                 "QDateTimeEdit::up-button:pressed {\n "
                                 "    color: #aeaeae;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n "
                                 "}\n"
                                 "QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, "
                                 "QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, "
                                 "QDateTimeEdit::down-button:pressed {\n "
                                 "    color: #aeaeae;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n "
                                 "}\n"
                                 "QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, "
                                 "QTimeEdit::up-button:hover, QDateEdit::up-button:hover, "
                                 "QDateTimeEdit::up-button:hover {\n "
                                 "    color: #FFFFFF;\n"
                                 "    border-top-right-radius: 5px;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #84afe5, stop:1 #1168e4);\n "
                                 "    \n"
                                 "}\n"
                                 "QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, "
                                 "QTimeEdit::down-button:hover, QDateEdit::down-button:hover, "
                                 "QDateTimeEdit::down-button:hover {\n "
                                 "    color: #FFFFFF;\n"
                                 "    border-bottom-right-radius: 5px;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #84afe5, stop:1 #1168e4);\n "
                                 "}\n"
                                 "QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, "
                                 "QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n "
                                 "    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
                                 "}\n"
                                 "QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, "
                                 "QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n "
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n "
                                 "}\n"
                                 "QProgressBar {\n"
                                 "    max-height: 8px;\n"
                                 "    text-align: center;\n"
                                 "    font: italic bold 11px;\n"
                                 "    color: #3d3d3d;\n"
                                 "    border: 1px solid transparent;\n"
                                 "    border-radius:4px;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                 "stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n "
                                 "}\n"
                                 "QProgressBar::chunk {\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                 "stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n "
                                 "    border-radius: 4px;\n"
                                 "}\n"
                                 "QProgressBar:disabled {\n"
                                 "    color: #616161;\n"
                                 "}\n"
                                 "QProgressBar::chunk:disabled {\n"
                                 "    background-color: #aeaeae;\n"
                                 "}\n"
                                 "QSlider::groove {\n"
                                 "    border: 1px solid #bbbbbb;\n"
                                 "    background-color: #52595d;\n"
                                 "    border-radius: 4px;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    height: 6px;\n"
                                 "}\n"
                                 "QSlider::groove:vertical {\n"
                                 "    width: 6px;\n"
                                 "}\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background: #ffffff;\n"
                                 "    border-style: solid;\n"
                                 "    border-width: 1px;\n"
                                 "    border-color: rgb(207,207,207);\n"
                                 "    width: 12px;\n"
                                 "    margin: -5px 0;\n"
                                 "    border-radius: 7px;\n"
                                 "}\n"
                                 "QSlider::handle:vertical {\n"
                                 "    background: #ffffff;\n"
                                 "    border-style: solid;\n"
                                 "    border-width: 1px;\n"
                                 "    border-color: rgb(207,207,207);\n"
                                 "    height: 12px;\n"
                                 "    margin: 0 -5px;\n"
                                 "    border-radius: 7px;\n"
                                 "}\n"
                                 "QSlider::add-page, QSlider::sub-page {\n"
                                 "    border: 1px transparent;\n"
                                 "    background-color: #52595d;\n"
                                 "    border-radius: 4px;\n"
                                 "}\n"
                                 "QSlider::add-page:horizontal {\n"
                                 "background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, "
                                 "stop:0.5 #dad3d3, stop:1 #ddd5d5);\n "
                                 "}\n"
                                 "QSlider::sub-page:horizontal {\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
                                 "stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n "
                                 "}\n"
                                 "QSlider::add-page:vertical {\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                 "stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n "
                                 "}\n"
                                 "QSlider::sub-page:vertical {\n"
                                 "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, "
                                 "stop:0.5 #dad3d3, stop:1 #ddd5d5);\n "
                                 "}\n"
                                 "QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, "
                                 "QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n "
                                 "    background: #b9b9b9;\n"
                                 "}\n"
                                 "QComboBox, QFontComboBox {\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius: 8px;\n"
                                 "    border-style: solid;\n"
                                 "border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, "
                                 "stop:0 #c1c9cf, stop:1 #d2d8dd);\n "
                                 "    background-color: #f4f4f4;\n"
                                 "    color: #272727;\n"
                                 "    padding-left: 5px;\n"
                                 "}\n"
                                 "QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, "
                                 "QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n "
                                 "    background: #ffffff;\n"
                                 "}\n"
                                 "QComboBox::drop-down {\n"
                                 "    subcontrol-origin: padding;\n"
                                 "    subcontrol-position: top right;\n"
                                 "    width: 15px;\n"
                                 "    color: #272727;\n"
                                 "    border-left-width: 1px;\n"
                                 "    border-left-color: darkgray;\n"
                                 "    border-left-style: solid;\n"
                                 "    border-top-right-radius: 3px;\n"
                                 "    border-bottom-right-radius: 3px;\n"
                                 "}\n"
                                 "QComboBox::down-arrow {\n"
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); "
                                 "/*Adawaita icon thene*/\n "
                                 "}\n"
                                 "\n"
                                 "QComboBox::down-arrow:on {\n"
                                 "    top: 1px;\n"
                                 "    left: 1px;\n"
                                 "}\n"
                                 "QComboBox QAbstractItemView {\n"
                                 "    border: 1px solid darkgray;\n"
                                 "    border-radius: 8px;\n"
                                 "    selection-background-color: #dadada;\n"
                                 "    selection-color: #272727;\n"
                                 "    color: #272727;\n"
                                 "    background: white;\n"
                                 "}\n"
                                 "QLabel, QCheckBox, QRadioButton {\n"
                                 "    color: #272727;\n"
                                 "}\n"
                                 "QCheckBox {\n"
                                 "    padding: 2px;\n"
                                 "}\n"
                                 "QCheckBox:disabled, QRadioButton:disabled {\n"
                                 "    color: #808086;\n"
                                 "    padding: 2px;\n"
                                 "}\n"
                                 "\n"
                                 "QCheckBox:hover {\n"
                                 "    border-radius:4px;\n"
                                 "    border-style:solid;\n"
                                 "    padding-left: 1px;\n"
                                 "    padding-right: 1px;\n"
                                 "    padding-bottom: 1px;\n"
                                 "    padding-top: 1px;\n"
                                 "    border-width:1px;\n"
                                 "    border-color: transparent;\n"
                                 "}\n"
                                 "QCheckBox::indicator:checked {\n"
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/object-select-symbolic.symbolic"
                                 ".png);\n "
                                 "    height: 15px;\n"
                                 "    width: 15px;\n"
                                 "    border-style:solid;\n"
                                 "    border-width: 1px;\n"
                                 "    border-color: #48a5fd;\n"
                                 "    color: #ffffff;\n"
                                 "    border-radius: 3px;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                 "stop:0 #48a5fd, stop:0.5 #329cfb, stop:1 #48a5fd);\n "
                                 "}\n"
                                 "QCheckBox::indicator:unchecked {\n"
                                 "    \n"
                                 "    height: 15px;\n"
                                 "    width: 15px;\n"
                                 "    border-style:solid;\n"
                                 "    border-width: 1px;\n"
                                 "    border-color: #48a5fd;\n"
                                 "    border-radius: 3px;\n"
                                 "    background-color: #fbfdfa;\n"
                                 "}\n"
                                 "QLCDNumber {\n"
                                 "    color: #616161;;\n"
                                 "}\n"
                                 "QMenuBar {\n"
                                 "    background-color: #ececec;\n"
                                 "}\n"
                                 "QMenuBar::item {\n"
                                 "    color: #616161;\n"
                                 "    spacing: 3px;\n"
                                 "    padding: 1px 4px;\n"
                                 "    background-color: #ececec;\n"
                                 "}\n"
                                 "\n"
                                 "QMenuBar::item:selected {\n"
                                 "    background-color: #dadada;\n"
                                 "    color: #3d3d3d;\n"
                                 "}\n"
                                 "QMenu {\n"
                                 "    background-color: #ececec;\n"
                                 "}\n"
                                 "QMenu::item:selected {\n"
                                 "    background-color: #dadada;\n"
                                 "    color: #3d3d3d;\n"
                                 "}\n"
                                 "QMenu::item {\n"
                                 "    color: #616161;;\n"
                                 "    background-color: #e0e0e0;\n"
                                 "}\n"
                                 "QTabWidget {\n"
                                 "    color:rgb(0,0,0);\n"
                                 "    background-color:#000000;\n"
                                 "}\n"
                                 "QTabWidget::pane {\n"
                                 "    border-color: #050a0e;\n"
                                 "    background-color: #e0e0e0;\n"
                                 "    border-width: 1px;\n"
                                 "    border-radius: 4px;\n"
                                 "    position: absolute;\n"
                                 "    top: -0.5em;\n"
                                 "    padding-top: 0.5em;\n"
                                 "}\n"
                                 "\n"
                                 "QTabWidget::tab-bar {\n"
                                 "    alignment: center;\n"
                                 "}\n"
                                 "\n"
                                 "QTabBar::tab {\n"
                                 "    border-bottom: 1px solid #c0c0c0;\n"
                                 "    padding: 3px;\n"
                                 "    color: #272727;\n"
                                 "    background-color: #fefefc;\n"
                                 "    margin-left:0px;\n"
                                 "}\n"
                                 "QTabBar::tab:!last {\n"
                                 "    border-right: 1px solid;\n"
                                 "    border-right-color: #c0c0c0;\n"
                                 "    border-bottom-color: #c0c0c0;\n"
                                 "}\n"
                                 "QTabBar::tab:first {\n"
                                 "    border-top-left-radius: 4px;\n"
                                 "    border-bottom-left-radius: 4px;\n"
                                 "}\n"
                                 "QTabBar::tab:last {\n"
                                 "    border-top-right-radius: 4px;\n"
                                 "    border-bottom-right-radius: 4px;\n"
                                 "}\n"
                                 "QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
                                 "    color: #FFFFFF;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, "
                                 "stop:0 #84afe5, stop:1 #1168e4);\n "
                                 "}\n"
                                 "QRadioButton::indicator {\n"
                                 "    height: 14px;\n"
                                 "    width: 14px;\n"
                                 "    border-style:solid;\n"
                                 "    border-radius:7px;\n"
                                 "    border-width: 1px;\n"
                                 "}\n"
                                 "QRadioButton::indicator:checked {\n"
                                 "    border-color: #48a5fd;\n"
                                 "background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, "
                                 "stop:0 #ffffff, stop:0.5 #ffffff, stop:0.6 #48a5fd, stop:1 #48a5fd);\n "
                                 "}\n"
                                 "QRadioButton::indicator:!checked {\n"
                                 "    border-color: #a9b7c6;\n"
                                 "    background-color: #fbfdfa;\n"
                                 "}\n"
                                 "QStatusBar {\n"
                                 "    color:#027f7f;\n"
                                 "}\n"
                                 "\n"
                                 "QDial {\n"
                                 "    background: #16a085;\n"
                                 "}\n"
                                 "\n"
                                 "QToolBox {\n"
                                 "    color: #a9b7c6;\n"
                                 "    background-color: #222b2e;\n"
                                 "}\n"
                                 "QToolBox::tab {\n"
                                 "    color: #a9b7c6;\n"
                                 "    background-color:#222b2e;\n"
                                 "}\n"
                                 "QToolBox::tab:selected {\n"
                                 "    color: #FFFFFF;\n"
                                 "    background-color:#222b2e;\n"
                                 "}\n"
                                 "QScrollArea {\n"
                                 "    color: #FFFFFF;\n"
                                 "    background-color:#222b2e;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar:horizontal {\n"
                                 "    max-height: 10px;\n"
                                 "    border: 1px transparent grey;\n"
                                 "    margin: 0px 20px 0px 20px;\n"
                                 "    background: transparent;\n"
                                 "}\n"
                                 "QScrollBar:vertical {\n"
                                 "    max-width: 10px;\n"
                                 "    border: 1px transparent grey;\n"
                                 "    margin: 20px 0px 20px 0px;\n"
                                 "    background: transparent;\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
                                 "    background: #52595d;\n"
                                 "    border-style: transparent;\n"
                                 "    border-radius: 4px;\n"
                                 "    min-height: 25px;\n"
                                 "}\n"
                                 "QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
                                 "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, "
                                 "stop:0.5 #3b88fc, stop:1 #467dd1);\n "
                                 "}\n"
                                 "QScrollBar::add-line, QScrollBar::sub-line {\n"
                                 "    border: 2px transparent grey;\n"
                                 "    border-radius: 4px;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "    background: #b9b9b9;\n"
                                 "}\n"
                                 "QScrollBar::add-line:horizontal {\n"
                                 "    width: 20px;\n"
                                 "    subcontrol-position: right;\n"
                                 "}\n"
                                 "QScrollBar::add-line:vertical {\n"
                                 "    height: 20px;\n"
                                 "    subcontrol-position: bottom;\n"
                                 "}\n"
                                 "QScrollBar::sub-line:horizontal {\n"
                                 "    width: 20px;\n"
                                 "    subcontrol-position: left;\n"
                                 "}\n"
                                 "QScrollBar::sub-line:vertical {\n"
                                 "    height: 20px;\n"
                                 "    subcontrol-position: top;\n"
                                 "}\n"
                                 "QScrollBar::add-line:vertical:pressed, QScrollBar::add-line:horizontal:pressed, "
                                 "QScrollBar::sub-line:horizontal:pressed, QScrollBar::sub-line:vertical:pressed {\n "
                                 "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, "
                                 "stop:0.5 #3b88fc, stop:1 #467dd1);\n "
                                 "}\n"
                                 "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, "
                                 "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n "
                                 "    background: none;\n"
                                 "}\n"
                                 "QScrollBar::up-arrow:vertical {\n"
                                 "    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
                                 "}\n"
                                 "QScrollBar::down-arrow:vertical {\n"
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n "
                                 "}\n"
                                 "QScrollBar::left-arrow:horizontal {\n"
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/go-previous-symbolic.symbolic.png"
                                 ");\n "
                                 "}\n"
                                 "QScrollBar::right-arrow:horizontal {\n"
                                 "image: url(/usr/share/icons/Adwaita/16x16/actions/go-next-symbolic.symbolic.png);\n "
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.AxialSlider = QtWidgets.QSlider(self.centralwidget)
        self.AxialSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AxialSlider.setObjectName("AxialSlider")
        self.verticalLayout.addWidget(self.AxialSlider)

        self.AxialView = Figure()
        self.axes = self.AxialView.add_subplot(1, 1, 1)
        self.axes.axis("off")
        self.canvas3 = FigureCanvas(self.AxialView)
        self.canvas3.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout.addWidget(self.canvas3)

        self.labelAxial = QtWidgets.QLabel(self.centralwidget)
        self.labelAxial.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.labelAxial.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelAxial.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAxial.setObjectName("labelAxial")
        self.verticalLayout.addWidget(self.labelAxial)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PathEdit.setObjectName("PathEdit")
        self.verticalLayout_4.addWidget(self.PathEdit)

        self.figure1 = Figure()
        self.axes1 = self.figure1.add_subplot(1, 3, 1)
        self.axes2 = self.figure1.add_subplot(1, 3, 2)
        self.axes3 = self.figure1.add_subplot(1, 3, 3)
        self.axes1.axis("off")
        self.axes2.axis("off")
        self.axes3.axis("off")
        self.canvas = FigureCanvas(self.figure1)
        self.canvas.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_4.addWidget(self.canvas)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_4.setStretch(1, 90)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoronalSlider = QtWidgets.QSlider(self.centralwidget)
        self.CoronalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CoronalSlider.setObjectName("CoronalSlider")
        self.verticalLayout_2.addWidget(self.CoronalSlider)

        self.CoronalView = Figure()
        self.axes_cor = self.CoronalView.add_subplot(1, 1, 1)
        self.axes_cor.axis("off")
        self.canvas1 = FigureCanvas(self.CoronalView)
        self.canvas1.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_2.addWidget(self.canvas1)

        self.labelCoronal = QtWidgets.QLabel(self.centralwidget)
        self.labelCoronal.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.labelCoronal.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelCoronal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCoronal.setObjectName("labelCoronal")
        self.verticalLayout_2.addWidget(self.labelCoronal)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SagittalSlider = QtWidgets.QSlider(self.centralwidget)
        self.SagittalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SagittalSlider.setObjectName("SagittalSlider")
        self.verticalLayout_3.addWidget(self.SagittalSlider)

        self.SagittalView = Figure()
        self.axes_sag = self.SagittalView.add_subplot(1, 1, 1)
        self.axes_sag.axis("off")
        self.canvas2 = FigureCanvas(self.SagittalView)
        self.canvas2.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_3.addWidget(self.canvas2)

        self.labelSagittal = QtWidgets.QLabel(self.centralwidget)
        self.labelSagittal.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.labelSagittal.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelSagittal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSagittal.setObjectName("labelSagittal")
        self.verticalLayout_3.addWidget(self.labelSagittal)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.Open = QtWidgets.QAction(MainWindow)
        self.Open.setObjectName("Open")
        self.File.addAction(self.Open)
        self.menubar.addAction(self.File.menuAction())
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brain Viewer"))

        self.File.setTitle(_translate("MainWindow", "File"))
        self.Open.setText(_translate("MainWindow", "Open"))
        self.labelAxial.setText(_translate("MainWindow", "AxialView"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.labelCoronal.setText(_translate("MainWindow", "CoronalView"))
        self.labelSagittal.setText(_translate("MainWindow", "SagittalView"))



# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
