# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QFileDialog
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.AxialSlider = QtWidgets.QSlider(self.centralwidget)
        self.AxialSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AxialSlider.setObjectName("AxialSlider")
        self.verticalLayout.addWidget(self.AxialSlider)

        self.AxialView = Figure()
        self.AxialView.patch.set_facecolor("black")
        self.axes = self.AxialView.add_subplot(1, 1, 1)
        self.axes.axis("off")
        self.canvas3 = FigureCanvas(self.AxialView)
        self.canvas3.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout.addWidget(self.canvas3)

        self.labelAxial = QtWidgets.QLabel(self.centralwidget)
        self.labelAxial.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
       # self.labelAxial.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelAxial.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAxial.setObjectName("labelAxial")
        self.verticalLayout.addWidget(self.labelAxial)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")


        self.figure1 = Figure()
        self.axes1 = self.figure1.add_subplot(1, 1, 1)
        self.figure1.patch.set_facecolor("black")
        self.axes1.axis("off")
        self.canvas = FigureCanvas(self.figure1)
        self.canvas.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_4.addWidget(self.canvas)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        #self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_4.setStretch(1, 90)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoronalSlider = QtWidgets.QSlider(self.centralwidget)
        self.CoronalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CoronalSlider.setObjectName("CoronalSlider")
        self.verticalLayout_2.addWidget(self.CoronalSlider)

        self.CoronalView = Figure()
        self.CoronalView.patch.set_facecolor("black")
        self.axes_cor = self.CoronalView.add_subplot(1, 1, 1)
        self.axes_cor.axis("off")
        self.canvas1 = FigureCanvas(self.CoronalView)
        self.canvas1.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_2.addWidget(self.canvas1)

        self.labelCoronal = QtWidgets.QLabel(self.centralwidget)
        self.labelCoronal.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        #self.labelCoronal.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelCoronal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCoronal.setObjectName("labelCoronal")
        self.verticalLayout_2.addWidget(self.labelCoronal)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SagittalSlider = QtWidgets.QSlider(self.centralwidget)
        self.SagittalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SagittalSlider.setObjectName("SagittalSlider")
        self.verticalLayout_3.addWidget(self.SagittalSlider)

        self.SagittalView = Figure()
        self.SagittalView.patch.set_facecolor("black")
        self.axes_sag = self.SagittalView.add_subplot(1, 1, 1)
        self.axes_sag.axis("off")
        self.canvas2 = FigureCanvas(self.SagittalView)
        self.canvas2.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.verticalLayout_3.addWidget(self.canvas2)

        self.labelSagittal = QtWidgets.QLabel(self.centralwidget)
        self.labelSagittal.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        #self.labelSagittal.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelSagittal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSagittal.setObjectName("labelSagittal")
        self.verticalLayout_3.addWidget(self.labelSagittal)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.Open = QtWidgets.QAction(MainWindow)
        self.Open.setObjectName("Open")
        self.File.addAction(self.Open)
        self.menubar.addAction(self.File.menuAction())
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brain Viewer"))

        self.File.setTitle(_translate("MainWindow", "File"))
        self.Open.setText(_translate("MainWindow", "Open"))
        self.labelAxial.setText(_translate("MainWindow", "AxialView"))
        self.label.setText(_translate("MainWindow", "GIF"))
        self.labelCoronal.setText(_translate("MainWindow", "CoronalView"))
        self.labelSagittal.setText(_translate("MainWindow", "SagittalView"))



